commands/pipelines/promote.js, test/commands/pipelines/promote.js
This still requires more requests than I'd like, it'd be great to allow the `targets` hash to be excluded entirely in the API.
```bash
❯ heroku pipelines:promote -a edamame-dev
Fetching app info... done
Fetching apps from edamame... done
Starting promotion to staging... done
Waiting for promotion to complete... done
Promotion successful
Edamame-Staging:    succeeded
Edamame-Staging-Eu: succeeded
```
=> Update CLI to use promotions endpoint

commands/pipelines/promote.js
If specified, the source app will be promoted to the list of target apps specified
instead of being promoted to all apps in the next stage.
=> Promote now accepts the --to flag.

commands/pipelines/add.js, commands/pipelines/create.js, commands/pipelines/info.js, lib/infer.js, lib/stages.js, test/lib/infer.js
- Factor out stage information to a single file.
- Stop suggesting `qa` and `test` stages.
=> Remove redundant stages

commands/pipelines/add.js, commands/pipelines/create.js, commands/pipelines/diff.js, commands/pipelines/remove.js, commands/pipelines/update.js, lib/api.js, test/commands/pipelines/add.js, test/commands/pipelines/create.js, test/commands/pipelines/remove.js, test/commands/pipelines/update.js
Changes all usages of `POST/PATCH/DELETE /apps/:id/pipeline-couplings` to use
* `POST /pipeline-couplings`
* `PATCH /pipeline-couplings/:id`
* `DELETE /pipeline-couplings/:id`
To resolve `pipeline-coupling:id` an API call is made to `GET /apps/:id/pipeline-couplings`.
=> Use new pipeline-couplings endpoints

lib/stages.js, test/lib/infer.js
We automatically create pipeline associations to review apps when the pipeline is created or when a review app is created in a pipeline.
I believe having this option available in the CLI creates confusion.
=> Disable selection of review stage

commands/pipelines/diff.js
include link to github diff in output, its common for us to generate that link and paste into hipchat.
```
> h pipelines:diff -a dev-herokuconnect
Fetching apps from pipeline... done
Fetching release info for all apps... done
=== dev-herokuconnect is ahead of herokuconnect-prod-eu by 12 commits
SHA      Date                  Author                 Message
───────  ────────────────────  ─────────────────────  ──────────────────────────────────────────────────────────────────
1788df5  2016-04-01T20:48:46Z  Marc Sibson            Merge pull request #3009 from heroku/doc-instance
2600f8f  2016-04-01T20:28:56Z  Marc Sibson            use INSTANCE as more decriptive than TARGET
c6ebc91  2016-04-01T20:08:03Z  Christopher Lambacher  Merge pull request #3006 from …
```
=> include link to github diff in output

commands/pipelines/add.js, commands/pipelines/create.js, commands/pipelines/info.js, lib/infer.js, lib/stages.js
It seems that when #22 was merged, `pipelines:info` stopped showing review apps being a part of the pipeline.
This change addresses that by bringing them back.
=> Re-add review apps to pipelines:info

lib/disambiguate.js, package.json
Removes the last remaining references to the `3.pipelines` API variant. The motivation for this is to clear out deprecation noise in the server side logs.
=> Stop using 3.pipelines variant

.jshintrc, commands/pipelines/promote.js
Currently the promotion endpoint can fail for apps which require 2FA because it re-runs all requests after prompting for a second factor. If the supplied second factor is counter based (e.g. a yubikey) then it expires after the first request.
This change explicitly wraps the only request which may require 2FA and retries it if necessary.
=> Explicit 2FA check on promotion endpoint

commands/pipelines/diff.js
Just a small fix to the wording of `pipelines:diff`'s help string.
=> Fix typo in help string

commands/pipelines/create.js, commands/pipelines/setup.js, lib/api.js, lib/disambiguate.js, lib/github-api.js, lib/kolkrabbi-api.js, lib/prompt.js, package.json, test/commands/pipelines/setup.js, test/mocha.opts
A single boostrap command allowing a new pipeline to be configured with sensible defaults:
```bash
❯ h pipelines:setup sausagess appleton/sausages -o heroku-devex
? Automatically deploy the master branch to staging? Yes
? Wait for CI to pass before deploying the master branch to staging? Yes
? Enable review apps? Yes
? Automatically create review apps for every PR? Yes
? Automatically destroy idle review apps after 5 days? Yes
? Enable automatic Heroku CI test runs? Yes
Creating pipeline... done
Linking to repo... done
Creating ⬢ sausagess (production app)... done
Creating ⬢ sausagess-staging (staging app)... done
Configuring pipeline... ⣻
Configuring pipeline... done
View your new pipeline by running `heroku pipelines:open 073d2f38-96df-4709-9a6d-eb9a55360921`
```
=> heroku pipelines:setup command

README.md, circle.yml, package.json
Also it uses Heroku DevCenter docs exclusively for reference, so we don't have to maintain the same information in both places both in the README and https://devcenter.heroku.com/articles/pipelines.
=> Add codecov coverage

commands/pipelines/setup.js, test/commands/pipelines/setup.js
Nyata can now create the pipeline coupling for us so we don't have to do it separately.
=> Use app-setups built in pipeline support

commands/pipelines/setup.js, lib/api.js, test/commands/pipelines/setup.js
For the command `pipeline:setup`, apps are created via the endpoint `POST /app-setup` in which a successful status response doesn't necessarily mean the apps were successfully created. These return `pending` and, in order to check out the status, it is necessarily to poll its status independently:
https://devcenter.heroku.com/articles/platform-api-reference#app-setup-info
Currently, the UX is is confusing since the pipeline setup carries on ending up with an empty pipeline page in dashboard if apps weren't successfully created (built).
This PR changes slightly the behavior to provide meaningful information in case something fails.
Demo:
**With an incorrect setup**:
**With a valid app.json**:
=> Show errors during app creation for pipeline:setup

index.js
IDEs which create swap files (such as vim) will prevent using this plugin linked, as it will try to load a non-js file.
=> Only load *.js files from commands

commands/pipelines/promote.js, package.json, test/commands/pipelines/promote.js
In the case of a promotion with a single target, we will fetch the release, look for `output_stream_url` and, if it is present, stream the data it returns.
@heroku/devex this is to start discussion. You might have a better implementation.
cc @heroku/build
=> Display the release command output if it is available

commands/pipelines/promote.js, test/commands/pipelines/promote.js
If api doesn't return a release phase output, we need to keep polling until the promotion status is succeeded, not return the targets right away.
=> Keep polling if there's no release phase output

index.js
This will be useful to disambiguate pipelines in other CLI clients.
Tested in `heroku-ci` (in this [PR](https://github.com/heroku/heroku-ci/pull/33)), and it works just doing:
```js
const disambiguatePipeline = require('heroku-pipelines').disambiguatePipeline
// ....
pipeline = yield disambiguatePipeline(client, pipeline)
```
=> Export disambiguatePipeline function

commands/pipelines/diff.js
For some reason the CLI has stopped providing a `heroku.options.userAgent`. I'm not sure if that was ever part of the API but I've [opened an issue](https://github.com/heroku/cli/issues/479).
Passing undefined into got.get causes an error to throw which we'd be better off ignoring.
=> Only pass user-agent if it is present

CHANGELOG.md, commands/pipelines/info.js, lib/api.js, package.json, test/commands/pipelines/info.js, yarn.lock
While working on Pipelines Ownership, it's useful to show the pipeline owner, and with the use of `--with-owners`, show the owner of all pipeline couplings.
1. `heroku plugins:link .`
2. Run `pipelines:info` command with a pipeline you own.
**Before**
```
› heroku pipelines:info sausages
=== sausages
review:     sausages-staging-pr-28
sausages-staging-pr-30
sausages-staging-pr-16
sausages-staging-pr-25
sausages-staging-pr-26
sausages-staging-pr-19
sausages-staging-pr-23
staging:    andouille
sausages-are-not-paranoid
sausages-staging
production: sausages-eu
sausages
sausages-tokyo
```
**Now**
```
› heroku pipelines:info sausages
name:  sausages
owner: heroku-devex (team)
app name                     stage
───────────────────────────  ──────────
⬢ sausages-staging-pr-16     review
⬢ …
```
=> Shows pipeline owner

CHANGELOG.md, commands/pipelines/info.js
This is automatically shown in this Dev Center article: https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-pipelines-info-pipeline.
Forgot to do this in #67
=> Update help output for pipelines:info

CHANGELOG.md, commands/pipelines/info.js, lib/ownership.js, test/commands/pipelines/info.js
The checklist enumerates the tasks you set out to do before the PR becomes ready for review
We want to encourage users to set a single ownership model in their pipelines. The metrics around this command proved that it was worth adding a warning message advising them about this situation when proceeds.
This warning is only added to the `pipelines:info` command as it'd be API expensive to check pipeline coupling ownership in other commands which would slow down the experience considerably. 
- Download this code
- Run it locally doing `heroku plugins:link .`
- Run `heroku pipelines:info` in a pipeline you think it's suspicious of being in this situation.
- enumerate a *list* of steps that the reviewer may step through to fully experience the changeset being introduced
```
› heroku …
```
=> Show mixed ownership warning

CHANGELOG.md, commands/pipelines/add.js, commands/pipelines/update.js, package.json, yarn.lock
---
Thanks for your contribution to heroku-pipelines!
---
The checklist enumerates the tasks you set out to do before the PR becomes ready for review
- [n/a ] Write tests
- [n/a] Update Dev Center Docs (will be done with autocomplete is GA)
- [n/a] Publish a new entry to [Heroku Changelog](https://devcenter.heroku.com/changelog) (will be done with autocomplete is GA)
Adding flag options completions for autocomplete
Tab-complete (in zsh) to see list of pipeline options:
`$ heroku plugins:link heroku-ci`
`$ heroku plugins:update`
`$ heroku ci --pipeline=<TAB>` 
- If the changeset includes user-visible results, please include before and after screenshots
- If the changeset modifies a workflow, please a screencast/gif illustrating the interaction.
All users that have setup heroku-cli …
=> add --stage flag completion

CHANGELOG.md, commands/pipelines/info.js
Fixes serialization for `pipelines:info --json`. https://github.com/heroku/heroku-pipelines/pull/72 changed the serialization for that command changing `apps` to `pipelineApps`.
=> Fix serialization for pipelines:info

CHANGELOG.md, commands/pipelines/transfer.js, lib/api.js, test/commands/pipelines/create.js, test/commands/pipelines/setup.js, test/commands/pipelines/transfer.js
To support pipelines ownership
- `heroku pipelines:transfer $PIPELINE_NAME $TEAM_NAME`
- `heroku pipelines:transfer $PIPELINE_NAME $ACCOUNT_EMAIL`
```
$ heroku pipelines:transfer example me@example.com
Transferring example pipeline to the me@example.com account... done
$ heroku pipelines:transfer example acme-widgets
Transferring example pipeline to the acme-widgets team... done
```
All users of the plugin
None
=> Implement heroku pipelines:transfer command

commands/pipelines/info.js, commands/pipelines/transfer.js, lib/render-pipeline.js, test/commands/pipelines/info.js, test/commands/pipelines/transfer.js
For compatibility with the new endpoint.
`herkou pipelines:transfer $NEW_OWNER p- $PIPELINE_NAME_OR_ID`
```shell
$ heroku pipelines:transfer me@example.com -p example
=== example
app name              stage
────────────────────  ───────────
⬢ example-dev         development
⬢ example-staging     staging
⬢ example-prod        production
▸    This will transfer example and all of the listed apps to the me@example.com account
▸    to proceed, type edamame or re-run this command with --confirm example
> example
Transferring example pipeline to the me@example.com account... done
$ heroku pipelines:transfer acme-widgets -p example
=== example
app name              stage
────────────────────  ───────────
⬢ example-dev         development
⬢ example-staging     staging
⬢ example-prod …
```
=> Update transfer to new endpoint

.gitignore, package.json, yarn.lock
Fix https://github.com/heroku/heroku-pipelines/pull/85#issuecomment-366921650
@jdxcode publishing the package still fails on the registry of the new name. Are you taking care of that?
```
› np --any-branch
Publish a new version of @heroku-cli/plugin-pipelines (current: 2.5.1)
? Select semver increment or specify new version patch 	2.5.2
Commits:
- Add oclif/plugin-legacy as a dependency  efe44ce
- Add @oclif/dev-cli as a dependency  e991ac7
- Update yarn.lock  a726fd4
- Bring version back to 2.5.1.  6ef4509
- Update CHANGELOG.md  48cbb38
- Merge pull request #85 from heroku/oclif  0c5f913
- Update changelog  bac9e0b
- v2.5.2  ff4912b
- oclifify  8188dcd
? Will bump from 2.5.1 to 2.5.2. Continue? Yes
✔ Prerequisite check
✔ Git
✔ Cleanup
✔ Installing dependencies using Yarn
✔ Running tests …
```
=> Fix oclifify

CHANGELOG.md, index.js
In 125249b1ca, the `disambiguatePipeline` export was removed but the heroku-ci plugin [relies](https://github.com/heroku/heroku-ci/blob/98d57407d/lib/utils.js#L3) on this export.
Run `heroku ci:debug -p acme` in a repository where Heroku CI is enabled.
=> Fix exports

commands/pipelines/transfer.js
Replaced "Edamame" with "example"
---
Thanks for your contribution to heroku-pipelines!
---
The checklist enumerates the tasks you set out to do before the PR becomes ready for review
- [N/A] Write tests
- [N/A] Update yarn.lock
- [N/A] Update [CHANGELOG.md](https://github.com/heroku/heroku-pipelines/blob/master/CHANGELOG.md)
- [N/A] Update Dev Center Docs
- [N/A] Publish a new entry to [Heroku Changelog](https://devcenter.heroku.com/changelog)
The example given when checking the help menu on the command line is confusing as it mentions "edamame" as the name of the pipeline instead of "example".  
- enumerate a *list* of steps that the reviewer may step through to fully experience the changeset being introduced
From the command prompt, please run `heroku pipelines:transfer --help`.  You …
=> Typo in help text
